# Generated by Django 2.1 on 2018-09-06 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20180902_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='histoy_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('current_number_in_stock', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_model')),
            ],
        ),
    ]
