# Generated by Django 2.1 on 2018-09-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='number_in_stock',
            field=models.IntegerField(default=1),
        ),
    ]
