# Generated by Django 2.1 on 2018-09-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_model_number_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
